-- CreateTable
CREATE TABLE `arsip_sk_pensiun` (
    `id` VARCHAR(191) NOT NULL,
    `nomorSk` VARCHAR(191) NOT NULL,
    `tanggalSk` VARCHAR(191) NULL,
    `fileUrl` VARCHAR(191) NULL,
    `isDeleted` BOOLEAN NOT NULL DEFAULT false,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `arsip_sk_pensiun_nomorSk_key`(`nomorSk`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `data_p3k` (
    `id` VARCHAR(191) NOT NULL,
    `nipLama` VARCHAR(191) NULL,
    `nipBaru` VARCHAR(191) NOT NULL,
    `pnsId` VARCHAR(191) NOT NULL,
    `nama` VARCHAR(191) NOT NULL,
    `gelarDepan` VARCHAR(191) NULL,
    `gelarBelakang` VARCHAR(191) NULL,
    `tempatLahirId` VARCHAR(191) NULL,
    `tempatLahirNama` VARCHAR(191) NULL,
    `tanggalLahir` VARCHAR(191) NULL,
    `jenisKelamin` VARCHAR(191) NULL,
    `agamaId` VARCHAR(191) NULL,
    `agamaNama` VARCHAR(191) NULL,
    `jenisKawinId` VARCHAR(191) NULL,
    `jenisKawinNama` VARCHAR(191) NULL,
    `nik` VARCHAR(191) NULL,
    `nomorHp` VARCHAR(191) NULL,
    `email` VARCHAR(191) NULL,
    `emailGov` VARCHAR(191) NULL,
    `alamat` VARCHAR(191) NULL,
    `npwpNomor` VARCHAR(191) NULL,
    `bpjs` VARCHAR(191) NULL,
    `jenisPegawaiId` VARCHAR(191) NULL,
    `jenisPegawaiNama` VARCHAR(191) NULL,
    `kedudukanHukumId` VARCHAR(191) NULL,
    `kedudukanHukumNama` VARCHAR(191) NULL,
    `statusCpnsPns` VARCHAR(191) NULL,
    `kartuAsnVirtual` VARCHAR(191) NULL,
    `nomorSkCpns` VARCHAR(191) NULL,
    `tanggalSkCpns` VARCHAR(191) NULL,
    `tmtCpns` VARCHAR(191) NULL,
    `nomorSkPns` VARCHAR(191) NULL,
    `tanggalSkPns` VARCHAR(191) NULL,
    `tmtPns` VARCHAR(191) NULL,
    `golAwalId` VARCHAR(191) NULL,
    `golAwalNama` VARCHAR(191) NULL,
    `golAkhirId` VARCHAR(191) NULL,
    `golAkhirNama` VARCHAR(191) NULL,
    `tmtGolongan` VARCHAR(191) NULL,
    `mkTahun` VARCHAR(191) NULL,
    `mkBulan` VARCHAR(191) NULL,
    `jenisJabatanId` VARCHAR(191) NULL,
    `jenisJabatanNama` VARCHAR(191) NULL,
    `jabatanId` VARCHAR(191) NULL,
    `jabatanNama` VARCHAR(191) NULL,
    `tmtJabatan` VARCHAR(191) NULL,
    `tingkatPendidikanId` VARCHAR(191) NULL,
    `tingkatPendidikanNama` VARCHAR(191) NULL,
    `pendidikanId` VARCHAR(191) NULL,
    `pendidikanNama` VARCHAR(191) NULL,
    `tahunLulus` VARCHAR(191) NULL,
    `kpknId` VARCHAR(191) NULL,
    `kpknNama` VARCHAR(191) NULL,
    `lokasiKerjaId` VARCHAR(191) NULL,
    `lokasiKerjaNama` VARCHAR(191) NULL,
    `unorId` VARCHAR(191) NULL,
    `unorNama` VARCHAR(191) NULL,
    `instansiIndukId` VARCHAR(191) NULL,
    `instansiIndukNama` VARCHAR(191) NULL,
    `instansiKerjaId` VARCHAR(191) NULL,
    `instansiKerjaNama` VARCHAR(191) NULL,
    `satuanKerjaIndukId` VARCHAR(191) NULL,
    `satuanKerjaIndukNama` VARCHAR(191) NULL,
    `satuanKerjaKerjaId` VARCHAR(191) NULL,
    `satuanKerjaKerjaNama` VARCHAR(191) NULL,
    `isValidNik` VARCHAR(191) NULL,
    `namaSekolah` VARCHAR(191) NULL,
    `flagIkd` VARCHAR(191) NULL,
    `statusPensiun` VARCHAR(191) NULL DEFAULT 'AKTIF',
    `arsipSkPensiunId` VARCHAR(191) NULL,
    `isDeleted` BOOLEAN NOT NULL DEFAULT false,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `data_p3k_nipBaru_key`(`nipBaru`),
    UNIQUE INDEX `data_p3k_pnsId_key`(`pnsId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `data_p3k` ADD CONSTRAINT `data_p3k_arsipSkPensiunId_fkey` FOREIGN KEY (`arsipSkPensiunId`) REFERENCES `arsip_sk_pensiun`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
